#pragma once

#define DEFAULT_GAUSSIAN_STDDEV 30

#define DEFAULT_SALTPEPPER_PROBABILITY_LO 0.05
#define DEFAULT_SALTPEPPER_PROBABILITY_HI 0.95

#define DEFAULT_FILTER "cpu_simple"
#define DEFAULT_WINDOWSIZE 3

#cmakedefine ENABLE_FILTER_CPU
#cmakedefine ENABLE_FILTER_CUDA
#cmakedefine ENABLE_FILTER_ARRAYFIRE

#cmakedefine ENABLE_FEATURE_OPENMP

#define CUDA_TILE_SIZE_X 16
#define CUDA_TILE_SIZE_Y 16
