target_architecture(ARCHITECTURE)

#compiler
if("${CMAKE_CXX_COMPILER}" MATCHES "icl")
    set(COMPILER_INTEL 1)
endif()


#options for arch
if(ARCHITECTURE STREQUAL "i386" OR ARCHITECTURE STREQUAL "x86_64") 
    set(X86 1)
    if(ARCHITECTURE STREQUAL "i386")
        set(X86_bit 32)
        set(X86_32 1)
    else()
        set(X86_bit 64)
        set(X86_64 1)
    endif()
endif()

if(X86)
    option(X86_AVX "Enable AVX optimizations" OFF)
    option(X86_AVX2 "Enable AVX2 optimizations" OFF)
    
    if(MSVC AND X86_64)
        set(X86_SSE2 ON)
    else()
        option(X86_SSE2 "Enable SSE2 optimizations" ON)
    endif()
endif()

if(X86_SSE2)
    if(CMAKE_COMPILER_IS_GNUCC)
        set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -msse2")
        set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -msse2")
    elseif(MSVC AND NOT X86_64)
        set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} /arch:SSE2")
        set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} /arch:SSE2")
    endif()
endif()

if(X86_AVX)
    if(CMAKE_COMPILER_IS_GNUCC)
        set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -mavx")
        set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -mavx")
    elseif(COMPILER_INTEL OR MSVC)
        set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} /arch:AVX")
        set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} /arch:AVX")
    endif()
endif()

if(X86_AVX2)
    if(CMAKE_COMPILER_IS_GNUCC)
        set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -mavx2")
        set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -mavx2")
    elseif(COMPILER_INTEL OR MSVC)
        set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} /arch:CORE-AVX2")
        set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} /arch:CORE-AVX2")
    endif()
endif()

if(COMPILER_INTEL)
    set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} /debug:inline-debug-info")
    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} /debug:inline-debug-info")
endif()