message("/=================================")
message("|Arch             : " ${ARCHITECTURE})
if(X86)
message("|Arch/X86/AVX     : " ${X86_AVX})
message("|Arch/X86/AVX2    : " ${X86_AVX2})
message("|Arch/X86/SSE2    : " ${X86_SSE2})
endif()
message("|")
message("|Filter/CPU       : " ${ENABLE_FILTER_CPU})
message("|Filter/CUDA      : " ${ENABLE_FILTER_CUDA})
message("|Filter/ArrayFire : " ${ENABLE_FILTER_ARRAYFIRE})
message("|")
message("|Feature/OpenMP   : " ${ENABLE_FEATURE_OPENMP})
message("\\=================================")
